# Generated by Django 6.0.7 on 2026-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
