# Generated by Django 6.0.7 on 2026-08-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0003_address_building_address_county_address_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
    ]
