# Generated by Django 6.0.7 on 2026-08-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0004_remove_address_country_remove_address_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='county',
        ),
    ]
