# Generated by Django 6.0.7 on 2026-08-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0005_remove_address_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
    ]
