# Generated by Django 6.0.7 on 2026-08-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
