# Generated by Django 6.0.7 on 2026-08-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0013_apikey_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
