# Generated by Django 6.0.7 on 2026-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0014_apikey_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
