# Generated by Django 6.0.7 on 2026-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0015_profile_confirmation_code_profile_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
