# Generated by Django 6.0.7 on 2026-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0016_profile_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
