# Generated by Django 6.0.7 on 2026-08-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0017_profile_code_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
