# Generated by Django 6.0.7 on 2026-08-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0018_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
