# Generated by Django 6.0.7 on 2026-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0019_profile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
