# Generated by Django 6.1 on 2026-08-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0025_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
