# Generated by Django 6.1 on 2026-08-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0027_apikey_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='company',
        ),
    ]
