# Generated by Django 6.1 on 2026-08-15 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0028_remove_apikey_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_domains', to='integrator.account')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
