# Generated by Django 6.0.7 on 2026-08-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0029_apidomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='integrator.apidomain'),
        ),
    ]
