# Generated by Django 6.0.7 on 2026-08-15 11:48

import django.db.models.deletion
from django.db import migrations, models


def clear_domain_values(apps, schema_editor):
    schema_editor.execute(
        'ALTER TABLE integrator_apikey MODIFY COLUMN domain VARCHAR(255) NULL'
    )
    schema_editor.execute(
        'UPDATE integrator_apikey SET domain = NULL'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0029_apidomain'),
    ]

    operations = [
        migrations.RunPython(clear_domain_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='apikey',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='integrator.apidomain'),
        ),
    ]
