# Generated by Django 6.0.7 on 2026-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0030_alter_apikey_domain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apidomain',
            constraint=models.UniqueConstraint(fields=('id', 'account_id'), name='uniq_apidomain_id_account'),
        ),
    ]
