# Generated by Django 6.0.7 on 2026-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0031_apidomain_uniq_apidomain_id_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidomain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
