# Generated by Django 6.0.7 on 2026-08-16 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_customers(apps, schema_editor):
    Account = apps.get_model('integrator', 'Account')
    AccountCustomer = apps.get_model('integrator', 'AccountCustomer')
    Order = apps.get_model('payments', 'Order')
    created = 0
    for account in Account.objects.all().iterator():
        customer_ids = (
            Order.objects.filter(owner_id=account.user_id)
            .values_list('user_id', flat=True)
            .distinct()
        )
        for customer_id in customer_ids:
            _, was_created = AccountCustomer.objects.get_or_create(
                account_id=account.id, customer_id=customer_id
            )
            created += was_created
    return created


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0032_alter_apidomain_domain'),
        ('payments', '0054_project_account_service_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='integrator.account'),
        ),
        migrations.CreateModel(
            name='AccountCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='integrator.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'customer'), name='account_customer_unique')],
            },
        ),
        migrations.RunPython(backfill_customers, migrations.RunPython.noop),
    ]
