# Generated by Django 6.1 on 2026-08-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0033_company_account_accountcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
