# Generated by Django 6.1 on 2026-08-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0034_apikey_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcustomer',
            options={},
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrator.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
