# Generated by Django 6.0.7 on 2026-08-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='payments.order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='payments.project')),
            ],
            options={
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='projects', through='payments.ProjectOrder', to='payments.order'),
        ),
    ]
