# Generated by Django 6.0.7 on 2026-08-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_projectorder_project_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='orders',
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='payments.order'),
        ),
        migrations.DeleteModel(
            name='ProjectOrder',
        ),
    ]
