# Generated by Django 6.0.7 on 2026-08-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_project_orders_project_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.project'),
        ),
    ]
