# Generated by Django 6.0.7 on 2026-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_project_order_order_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_to',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=20),
        ),
    ]
