# Generated by Django 6.0.7 on 2026-08-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='material',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
    ]
