# Generated by Django 6.0.7 on 2026-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_material_amount_remove_material_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='materials',
            field=models.CharField(choices=[('included', 'Included'), ('not_included', 'Not included'), ('finish_not_included', 'Finish not included')], default='included', max_length=30),
        ),
    ]
