# Generated by Django 6.0.7 on 2026-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_order_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='available_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
