# Generated by Django 6.0.7 on 2026-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_project_available_from_project_available_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
