# Generated by Django 6.0.7 on 2026-08-02 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_order_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
