# Generated by Django 6.0.7 on 2026-08-02 13:21

from django.db import migrations

GROUPS = ['Customer', 'Employer', 'Administrator', 'Owner']


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in GROUPS:
        Group.objects.get_or_create(name=name)


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=GROUPS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_order_executors'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
