# Generated by Django 6.0.7 on 2026-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('hour', 'Hours'), ('day', 'Days'), ('sqm', 'm²'), ('meter', 'Meters'), ('box', 'Boxes')], default='pcs', max_length=30),
        ),
    ]
