# Generated by Django 6.0.7 on 2026-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_orderitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('pc', 'Pieces'), ('in', 'Inches'), ('ft', 'Feet'), ('m', 'Meters'), ('in2', 'Square inches'), ('ft2', 'Square feet'), ('m2', 'Square meters')], default='pc', max_length=30),
        ),
    ]
