# Generated by Django 6.0.7 on 2026-08-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0032_alter_apidomain_domain'),
        ('payments', '0021_category_full_name_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='integrator.account'),
        ),
    ]
