# Generated by Django 6.0.7 on 2026-08-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='payments.location'),
        ),
    ]
