# Generated by Django 6.0.7 on 2026-08-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_category_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='full_name',
        ),
    ]
