# Generated by Django 6.0.7 on 2026-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_remove_location_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('city', 'City'), ('county', 'County'), ('state', 'State')], max_length=20),
        ),
    ]
