# Generated by Django 6.0.7 on 2026-08-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
    ]
