# Generated by Django 6.0.7 on 2026-08-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_remove_location_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
