# Generated by Django 6.0.7 on 2026-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_rename_name_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='full_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='short_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('city', 'City'), ('county', 'County'), ('state', 'State')], max_length=20),
        ),
    ]
