# Generated by Django 6.0.7 on 2026-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0032_alter_apidomain_domain'),
        ('payments', '0030_location_city_location_country_location_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='category_account_name_unique'),
        ),
    ]
