# Generated by Django 6.0.7 on 2026-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0032_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
