# Generated by Django 6.0.7 on 2026-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='service',
            name='duration_end',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
