# Generated by Django 6.0.7 on 2026-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_remove_service_duration_service_duration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=20),
        ),
    ]
