# Generated by Django 6.0.7 on 2026-08-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_service_duration_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', max_length=20),
        ),
    ]
