# Generated by Django 6.0.7 on 2026-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_alter_service_duration_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
