# Generated by Django 6.0.7 on 2026-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_service_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
