# Generated by Django 6.0.7 on 2026-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_service_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='amount',
        ),
    ]
