# Generated by Django 6.0.7 on 2026-08-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_remove_service_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='payments.location'),
        ),
    ]
