# Generated by Django 6.0.7 on 2026-08-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_service_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
