# Generated by Django 6.0.7 on 2026-08-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_remove_category_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
    ]
