# Generated by Django 6.0.7 on 2026-08-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_remove_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='locations', to='payments.category'),
        ),
    ]
