# Generated by Django 6.0.7 on 2026-08-16 02:43

import django.db.models.deletion
from django.db import migrations, models


def copy_location_categories(apps, schema_editor):
    schema_editor.execute(
        "INSERT INTO locations_categories (location_id, category_id) "
        "SELECT location_id, category_id FROM payments_location_categories"
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payments', '0045_location_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='payments.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='payments.location')),
            ],
            options={
                'db_table': 'locations_categories',
            },
        ),
        migrations.RunPython(copy_location_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='locations', through='payments.LocationsCategories', to='payments.category'),
        ),
        migrations.AddConstraint(
            model_name='locationscategories',
            constraint=models.UniqueConstraint(fields=('location', 'category'), name='locations_categories_unique'),
        ),
    ]