# Generated by Django 6.0.7 on 2026-08-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payments', '0046_locationscategories_alter_location_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='payments.service')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='payments.location')),
            ],
            options={
                'db_table': 'location_items',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='categories',
        ),
        migrations.DeleteModel(
            name='LocationsCategories',
        ),
        migrations.AddField(
            model_name='location',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='locations', through='payments.LocationItems', to='payments.service'),
        ),
        migrations.AddConstraint(
            model_name='locationitems',
            constraint=models.UniqueConstraint(fields=('location', 'item'), name='location_items_unique'),
        ),
    ]