# Generated by Django 6.0.7 on 2026-08-16 02:56

import django.db.models.deletion
from django.db import migrations, models


def copy_location_services(apps, schema_editor):
    schema_editor.execute(
        "INSERT INTO location_services (location_id, service_id) "
        "SELECT location_id, item_id FROM location_items"
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('payments', '0047_locationitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='payments.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_links', to='payments.service')),
            ],
            options={
                'db_table': 'location_services',
            },
        ),
        migrations.RemoveConstraint(
            model_name='locationitems',
            name='location_items_unique',
        ),
        migrations.RemoveField(
            model_name='location',
            name='items',
        ),
        migrations.AddField(
            model_name='location',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='locations', through='payments.LocationServices', to='payments.service'),
        ),
        migrations.RunPython(copy_location_services, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='locationitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='locationitems',
            name='location',
        ),
        migrations.AddConstraint(
            model_name='locationservices',
            constraint=models.UniqueConstraint(fields=('location', 'service'), name='location_services_unique'),
        ),
        migrations.DeleteModel(
            name='LocationItems',
        ),
    ]