# Generated by Django 6.0.7 on 2026-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0050_serviceimage_uri_url_service_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
