# Generated by Django 6.0.7 on 2026-08-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0052_category_created_by_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
