# Generated by Django 6.0.7 on 2026-08-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0032_alter_apidomain_domain'),
        ('payments', '0053_project_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='integrator.account'),
        ),
        migrations.AddField(
            model_name='service',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='integrator.account'),
        ),
    ]
