# Generated by Django 6.0.7 on 2026-08-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0033_company_account_accountcustomer'),
        ('payments', '0054_project_account_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='integrator.account'),
        ),
    ]
